# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Notas de GMatheu
tagline:          ''
description:      '<br/><p>Notas y cosas que nunca me voy a acordar por <a href="https://twitter.com/gmatheu" target="_blank">@gmatheu</a>.</p>'
url:              http://gmatheu.github.io

author:
  name:           'Gonzalo Matheu'
  url:            https://twitter.com/gmatheu

paginate:         5

github:
  repo:           https://github.com/gmatheu/gmatheu.github.io
